//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PavlenkoFrolova.TechnoService.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Device
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public int DeviceTypeId { get; set; }
        public int OrderId { get; set; }
    
        public virtual DeviceType DeviceType { get; set; }
        public virtual Order Order { get; set; }
    }
}
