//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PavlenkoFrolova.TechnoService.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public Employee()
        {
            this.EmloyeeAccount = new HashSet<EmloyeeAccount>();
            this.Order = new HashSet<Order>();
        }
    
        public int Id { get; set; }
        public string Firsrname { get; set; }
        public string Lastname { get; set; }
        public string Middlename { get; set; }
        public System.DateTime DateOfBirth { get; set; }
        public string PhoneNumber { get; set; }
        public int PositionId { get; set; }
    
        public virtual ICollection<EmloyeeAccount> EmloyeeAccount { get; set; }
        public virtual Position Position { get; set; }
        public virtual ICollection<Order> Order { get; set; }
    }
}
