//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PavlenkoFrolova.TechnoService.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TechnoServiceEntities : DbContext
    {
        public TechnoServiceEntities()
            : base("name=TechnoServiceEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Client> Client { get; set; }
        public DbSet<Device> Device { get; set; }
        public DbSet<DeviceType> DeviceType { get; set; }
        public DbSet<EmloyeeAccount> EmloyeeAccount { get; set; }
        public DbSet<Employee> Employee { get; set; }
        public DbSet<FeedBack> FeedBack { get; set; }
        public DbSet<MalfunctionType> MalfunctionType { get; set; }
        public DbSet<Order> Order { get; set; }
        public DbSet<OrderStatus> OrderStatus { get; set; }
        public DbSet<Position> Position { get; set; }
        public DbSet<Role> Role { get; set; }
    }
}
