//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PavlenkoFrolova.TechnoService.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public Order()
        {
            this.Device = new HashSet<Device>();
        }
    
        public int Id { get; set; }
        public string Number { get; set; }
        public System.DateTime CreationDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public int MalfuctionTypeId { get; set; }
        public string Description { get; set; }
        public int ClientId { get; set; }
        public int OrderStatusId { get; set; }
        public int EmployeeId { get; set; }
        public int FeedBackId { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual ICollection<Device> Device { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual FeedBack FeedBack { get; set; }
        public virtual MalfunctionType MalfunctionType { get; set; }
        public virtual OrderStatus OrderStatus { get; set; }
    }
}
